// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2b79512a-0874-4357-85c8-ae6a89e1aa10",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qOGYydRmB",
    "aws_user_pools_web_client_id": "6nkc70lr464stlk5iu6bkhhn40",
    "oauth": {}
};


export default awsmobile;
